// pages/blogs/index.tsx
import Head from 'next/head'
import Link from "next/link"
import Image from 'next/image'
import { client } from "../../libs/client"
import styles from '@/styles/Blogs.module.scss'

export default function Blogs({ blogs }) {
  return (
    <>
      <Head>
        <title>ブログ</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.blogsArchive}>
          <ul className={styles.blofsList}>
            {blogs.map((blog) => (
              <li className={styles.blofsItem} key={blog.id}>
                <Link href={`/blogs/${blog.id}`}>
                  <div className={styles.blogsThumbnail}>
                    <Image
                      src={blog.eyecatch.url}
                      width={blog.eyecatch.width}
                      height={blog.eyecatch.height}
                      alt=""
                    />
                  </div>
                  <p className={styles.blogsTitle}>{blog.title}</p>
                </Link>
              </li>
            ))}
          </ul>
        </div>
      </main>
    </>
  );
}

// データをテンプレートに受け渡す部分の処理を記述します
export const getStaticProps = async () => {
  const data = await client.get({ endpoint: "blogs" });

  return {
    props: {
      blogs: data.contents,
    },
  };
};